export const MdSysColorShadow = "#000";
export const MdSysTypescaleButtonFont = "Roboto";
export const MdSysTypescaleButtonSize = "16";
export const mdSysColorOnSurfaceStateLayer = "16";
export const MdSysShapeCornerNone = "0";
export const MdSysShapeCornerExtraSmall = "4 4 4 4";
export const MdSysShapeCornerExtraSmallTop = "4 4 0 0";
export const MdSysShapeCornerSmall = "8 8 8 8";
export const MdSysShapeCornerMedium = "12 12 12 12";
export const MdSysShapeCornerLarge = "16 16 16 16";
export const MdSysShapeCornerLargeEnd = "0 16 16 0";
export const MdSysShapeCornerLargeTop = "16 16 0 0";
export const MdSysShapeCornerExtraLarge = "28 28 28 28";
export const MdSysShapeCornerExtraLargeTop = "28 28 0 0";
export const MdSysShapeCornerFull = "50% 50% 50% 50%"; // should be 50% of the short side
